### PR TITLE
Fix install requires

### PR DESCRIPTION
**Pull request by chrisjsewell**
> error in aiida-optimize setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers; Expected end or semicolon (after version specifier)

### CODE REVIEW

**Review by greschd — APPROVED** [review]
Thanks @chrisjsewell!

**Comment by greschd** [comment]
Let me know if you'll need a patch release for this.

**Comment by chrisjsewell** [comment]
> Let me know if you'll need a patch release for this.

yep that would be great thanks 😄

**Comment by greschd** [comment]
Ok, I'll do that tonight.

**Comment by greschd** [comment]
Aah sorry, I hadn't noticed that the pipelines need approval. Seems they need some attention, let me see if I can polish those...

Should probably upgrade the dependency management to poetry+dependabot at some point.

**Comment by greschd** [comment]
https://pypi.org/project/aiida-optimize/1.0.2

**Pull request merged**
